# Generated by Django 4.2.1 on 2023-06-03 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('date_of_completion', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the service to perform', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming', models.CharField(help_text='Enter the service pack naming', max_length=200)),
                ('order', models.ManyToManyField(blank=True, null=True, to='cleaning.order')),
                ('service', models.ManyToManyField(help_text='Select a service for this service pack', to='cleaning.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for particular Service Pack', primary_key=True, serialize=False)),
                ('price', models.IntegerField(max_length=10)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'Out of stock'), ('c', 'Coming soon')], default='a', help_text='Service pack availability', max_length=1)),
                ('service_pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cleaning.servicepack')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
