# Generated by Django 4.2.1 on 2023-06-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_alter_servicepack_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepack',
            name='order',
        ),
        migrations.AddField(
            model_name='servicepackinstance',
            name='order',
            field=models.ManyToManyField(blank=True, to='cleaning.order'),
        ),
    ]
