# Generated by Django 4.2.1 on 2023-06-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0003_remove_servicepack_order_servicepackinstance_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackinstance',
            name='order',
        ),
        migrations.AddField(
            model_name='servicepack',
            name='order',
            field=models.ManyToManyField(blank=True, to='cleaning.order'),
        ),
        migrations.AddField(
            model_name='servicepack',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
