# Generated by Django 4.2.1 on 2023-06-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0005_remove_servicepack_order_alter_servicepack_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepack',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
