# Generated by Django 4.2.1 on 2023-06-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0007_speed_delete_order_servicepack_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepack',
            name='speed',
        ),
        migrations.AddField(
            model_name='servicepackinstance',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Speed',
        ),
    ]
