# Generated by Django 4.2.1 on 2023-06-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0008_remove_servicepack_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackinstance',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
