# Generated by Django 4.2.1 on 2023-06-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0009_alter_servicepackinstance_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepack',
            name='price',
        ),
    ]
