# Generated by Django 4.2.1 on 2023-06-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0008_remove_servicepack_speed_and_more'),
        ('order', '0002_rename_book_orderitem_servicepack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='servicepack',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='servicepackinstance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='cleaning.servicepackinstance'),
        ),
    ]
